#!/bin/bash

die() {
    echo "$@" >&2
    exit 1
}

set -e

PROJECT="$1"

[ -z "$PROJECT" ] && die "usage: $0 PROJECT"

nix shell 'gitlab:haskell-wasm/ghc-wasm-meta?host=gitlab.haskell.org' --command \
    ./manage/wasm/build_wasm.after "$PROJECT"
